"""Log forensics: many log files generated by a small simulation, one root cause hidden in them.

Each scenario function returns ``(files, truth)``: ``files`` maps ``logs/<name>.log`` to a list of lines, ``truth`` says what the
answer is (culprit strings, kind, the lines that show it, key words for the explanation).  Log formats differ between tasks
(plain, logfmt, JSON lines), so the same scenario never looks the same twice.
"""
from __future__ import annotations

import json
import random
from datetime import datetime, timedelta, timezone

from fx import Task

from ._engine import KINDS, accepted, hidden_diag

T0 = datetime(2025, 3, 18, 6, 0, 0, tzinfo=timezone.utc)
STYLES = ["plain", "logfmt", "json"]
PATHS = ["/api/cart", "/api/search", "/api/orders", "/api/profile", "/api/checkout", "/static/app.js", "/api/inventory", "/healthz"]
WORDS = ["acorn", "bramble", "cedar", "dunlin", "egret", "fennel", "ginkgo", "heron", "iris", "juniper", "kestrel", "linden"]


class Log:
    """Formats lines in one style and keeps per-file line lists in time order."""

    def __init__(self, style: str, rng: random.Random):
        self.style, self.rng = style, rng
        self.files: dict[str, list[tuple[float, str]]] = {}
        self.t0 = T0

    def ts(self, t: float) -> str:
        d = self.t0 + timedelta(seconds=t)
        if self.style == "plain":
            return d.strftime("%b %d %H:%M:%S")
        return d.strftime("%Y-%m-%dT%H:%M:%S") + f".{int((t % 1) * 1000):03d}Z"

    def fmt(self, t: float, level: str, svc: str, host: str, msg: str, **kv) -> str:
        extra = "".join(f" {k}={v}" for k, v in kv.items())
        if self.style == "plain":
            return f"{self.ts(t)} {host} {svc}[{1000 + sum(map(ord, svc)) % 9000}]: {level.upper():5} {msg}{extra}"
        if self.style == "logfmt":
            q = msg.replace('"', "'")
            return f'ts={self.ts(t)} level={level} svc={svc} host={host} msg="{q}"{extra}'
        d = {"ts": self.ts(t), "level": level, "svc": svc, "host": host, "msg": msg}
        d.update({k: (int(v) if str(v).lstrip("-").isdigit() else v) for k, v in kv.items()})
        return json.dumps(d)

    def add(self, file: str, t: float, level: str, svc: str, host: str, msg: str, **kv) -> None:
        self.files.setdefault(file, []).append((t, self.fmt(t, level, svc, host, msg, **kv)))

    def finish(self) -> dict[str, list[str]]:
        out = {}
        for f, rows in self.files.items():
            rows.sort(key=lambda r: r[0])
            out[f] = [r[1] for r in rows]
        return out

    def where(self, file: str, needle: str, limit: int = 8) -> list[tuple[str, int]]:
        rows = sorted(self.files[file], key=lambda r: r[0])
        hits = [(file, i + 1) for i, (_, ln) in enumerate(rows) if needle in ln]
        return hits[:limit]


def _hosts(rng: random.Random, n: int) -> list[str]:
    pre = rng.choice(["web", "app", "edge", "node"])
    return [f"{pre}-{i + 1}" for i in range(n)]


def _requests(L: Log, rng: random.Random, hosts, t_end: int, per_host_rate: float, hook=None, svc="gateway", file_of=None):
    """Background traffic. hook(t, host, line_kv) may change level/msg/status; returns (level, msg, kv)."""
    for t in range(0, t_end):
        for h in hosts:
            if rng.random() > per_host_rate:
                continue
            path = rng.choice(PATHS)
            ms = max(3, int(rng.gauss(45, 15)))
            level, msg, kv = "info", "request served", {"path": path, "status": 200, "ms": ms}
            if rng.random() < 0.004:
                level, msg, kv = "warn", "client closed connection", {"path": path, "status": 499, "ms": ms}
            if hook:
                level, msg, kv = hook(t, h, level, msg, kv)
            L.add(file_of(h) if file_of else f"logs/{h}.log", t + rng.random() * 0.99, level, svc, h, msg, **kv)


# ---- scenarios ----------------------------------------------------------------------------------------------------

def scn_bad_host(rng: random.Random, L: Log):
    hosts = _hosts(rng, rng.randint(4, 7))
    bad = rng.choice(hosts)
    t_bad = rng.randint(200, 320)

    def hook(t, h, level, msg, kv):
        if h == bad and t >= t_bad and rng.random() < 0.75:
            return "error", "token rejected: not yet valid (iat is in the future)", {**kv, "status": 401}
        if rng.random() < 0.01:
            return "warn", "token rejected: bad signature", {**kv, "status": 401}
        return level, msg, kv

    _requests(L, rng, hosts, 600, 0.35, hook)
    for h in hosts:
        for t in range(0, 600, 60):
            off = round(rng.uniform(-0.04, 0.04), 3)
            if h == bad:
                off = round(0.02 + max(0, t - t_bad + 60) * 1.3, 3)
            L.add(f"logs/{h}.log", t + 0.5, "info", "chronyd", h, "clock offset", offset_s=off)
    L.add(f"logs/{bad}.log", t_bad - 20, "warn", "chronyd", bad, "lost all time sources, running free")
    anoms = L.where(f"logs/{bad}.log", "not yet valid", 6) + L.where(f"logs/{bad}.log", "lost all time sources", 1)
    return dict(
        symptom="Since a few minutes after 06:03 a share of logins is rejected with 401, but only some users complain and the load balancer says every backend is healthy.",
        culprit_desc="the host that causes it", culprit=[bad], kind="environment", anoms=anoms,
        kw=["clock", "ntp", "skew", "time", "chrony", "iat", "drift"], answer=f"{bad} has lost time sync (chronyd), its clock runs ahead, so tokens issued by the others look not-yet-valid to it.")


def scn_bad_release(rng: random.Random, L: Log):
    hosts = _hosts(rng, rng.randint(3, 5))
    old, new = "3.%d.%d" % (rng.randint(1, 9), rng.randint(0, 4)), "3.%d.%d" % (rng.randint(10, 19), rng.randint(0, 9))
    t_dep = rng.randint(220, 330)
    upgraded = rng.sample(hosts, max(2, len(hosts) // 2))
    L_t = {h: (t_dep + rng.randint(0, 120) if h in upgraded else None) for h in hosts}
    for h in hosts:
        L.add(f"logs/{h}.log", 0.2, "info", "orders", h, "starting", version=old)
        if L_t[h]:
            L.add(f"logs/{h}.log", L_t[h] - 1, "info", "deploy", h, "rolling restart", version=new)
            L.add(f"logs/{h}.log", L_t[h], "info", "orders", h, "starting", version=new)

    def hook_for(h):
        def hook(t, hh, level, msg, kv):
            ver = new if (L_t[h] and t >= L_t[h]) else old
            kv = {**kv, "ver": ver}
            if ver == new and kv["path"] in ("/api/orders", "/api/checkout") and rng.random() < 0.8:
                return "error", "KeyError: 'currency' while building invoice", {**kv, "status": 500}
            if rng.random() < 0.005:
                return "error", "upstream timeout", {**kv, "status": 504}
            return level, msg, kv
        return hook

    for h in hosts:
        _requests(L, rng, [h], 600, 0.45, hook_for(h), svc="orders")
    bad_hosts = [h for h in hosts if L_t[h]]
    anoms = []
    for h in bad_hosts[:3]:
        anoms += L.where(f"logs/{h}.log", "KeyError", 2)
    return dict(
        symptom="Checkout started failing with HTTP 500 around 06:04, on some servers but not on others; the on-call says nothing was changed except a rollout.",
        culprit_desc="the release version that introduced the failures", culprit=[new], kind="logic-error", anoms=anoms,
        kw=["currency", "release", "version", "deploy", "regression", "keyerror"], answer=f"Version {new} breaks invoice building (KeyError: 'currency'); only hosts that rolled to it fail.")


def scn_leak(rng: random.Random, L: Log):
    comps = rng.sample(["thumbnailer", "exporter", "mailer", "indexer", "scheduler", "importer"], 4)
    bad = rng.choice(comps)
    host = "batch-" + str(rng.randint(1, 4))
    base = {c: rng.randint(180, 420) for c in comps}
    kill_t = 3300
    for t in range(0, 3600, 60):
        for c in comps:
            rss = base[c] + rng.randint(-15, 15)
            kv = {"rss_mb": rss}
            if c == bad:
                kv["rss_mb"] = base[c] + int(t * 0.55) + rng.randint(-6, 6)
                kv["cache_entries"] = 120 + int(t * 9.5)
            elif rng.random() < 0.3:
                kv["cache_entries"] = 100 + rng.randint(-20, 20)
            if t <= kill_t or c != bad:
                L.add("logs/batch.log", t + 1, "info", c, host, "heartbeat", **kv)
            if rng.random() < 0.06:
                L.add("logs/batch.log", t + 7, "info", c, host, "job finished", jobs=rng.randint(1, 5))
    L.add("logs/batch.log", kill_t + 20, "error", "kernel", host, f"Out of memory: Killed process ({bad})", rss_mb=base[bad] + int(kill_t * 0.55))
    anoms = L.where("logs/batch.log", "Out of memory", 1)
    rows = sorted(L.files["logs/batch.log"], key=lambda r: r[0])
    anoms += [("logs/batch.log", i + 1) for i, (_, ln) in enumerate(rows) if bad in ln and "cache_entries" in ln][-4:]
    return dict(
        symptom="One of the batch processes was killed by the kernel just before 07:00; it was fine yesterday, and the machine has plenty of RAM for the usual load.",
        culprit_desc="the component that leaks", culprit=[bad], kind="resource-leak", anoms=anoms,
        kw=["leak", "memory", "rss", "cache", "grow", "evict", "oom"], answer=f"{bad} grows without bound (rss and cache_entries climb every minute) until the OOM killer takes it.")


def scn_race(rng: random.Random, L: Log):
    pairs = [("nightly-export", "reindex-orders", ("export", "reindex")), ("backup-snapshot", "vacuum-events", ("backup", "vacuum")),
             ("rebuild-search", "sync-catalog", ("rebuild", "catalog")), ("rotate-keys", "refresh-sessions", ("rotate", "refresh"))]
    a, b, stems = rng.choice(pairs)
    others = rng.sample(["cleanup-tmp", "send-digest", "warm-cache", "prune-audit", "poll-feeds"], 3)
    host = "cron-" + str(rng.randint(1, 3))
    anoms = []
    overlap_days = rng.choice([(2, 5), (1, 4, 6), (0, 3), (2, 4, 6)])
    for day in range(7):
        base = day * 3600
        # export and reindex run on most days, usually apart, on two days they overlap
        overlap = day in overlap_days
        sa = base + rng.randint(100, 300)
        da = rng.randint(500, 900)
        sb = sa + (rng.randint(100, da - 100) if overlap else da + rng.randint(60, 400))
        db = rng.randint(400, 800)
        for name, s, d in ((a, sa, da), (b, sb, db)):
            L.add("logs/jobs.log", s, "info", "scheduler", host, "job started", job=name, day=day + 1)
        if overlap:
            lo, hi = sb, min(sa + da, sb + db)
            n = rng.randint(2, 4)
            for k in range(n):
                tt = lo + (hi - lo) * (k + 1) / (n + 1)
                for who in (a, b):
                    if rng.random() < 0.8:
                        L.add("logs/jobs.log", tt + rng.random(), "error", who, host, "lock timeout after 30s waiting for table orders", day=day + 1)
            L.add("logs/jobs.log", sa + da, "error", "scheduler", host, "job failed", job=a, day=day + 1)
            L.add("logs/jobs.log", sb + db, "error", "scheduler", host, "job failed", job=b, day=day + 1)
        else:
            L.add("logs/jobs.log", sa + da, "info", "scheduler", host, "job finished", job=a, day=day + 1)
            L.add("logs/jobs.log", sb + db, "info", "scheduler", host, "job finished", job=b, day=day + 1)
        for o in others:
            s = base + rng.randint(1500, 3300)
            L.add("logs/jobs.log", s, "info", "scheduler", host, "job started", job=o, day=day + 1)
            L.add("logs/jobs.log", s + rng.randint(20, 300), "info", "scheduler", host, "job finished", job=o, day=day + 1)
            if rng.random() < 0.15:
                L.add("logs/jobs.log", s + rng.randint(5, 15), "warn", o, host, "slow response from dependency", ms=rng.randint(1200, 4000), day=day + 1)
    rows = sorted(L.files["logs/jobs.log"], key=lambda r: r[0])
    anoms = [("logs/jobs.log", i + 1) for i, (_, ln) in enumerate(rows) if "lock timeout" in ln][:5]
    return dict(
        symptom="Some nights one of the maintenance jobs fails with a lock timeout and the next night it is fine. Nobody can see a pattern.",
        culprit_desc="the two jobs whose overlap causes it, e.g. `a + b`", culprit_all=list(stems), kind="race-condition", anoms=anoms,
        kw=["overlap", "concurrent", "lock", "same time", "table"], answer=f"{a} and {b} fight for the orders table whenever they run at the same time.")


def scn_config_drift(rng: random.Random, L: Log):
    nodes = [f"n{i + 1}" for i in range(rng.randint(4, 6))]
    bad = rng.choice(nodes)
    key, good, wrong = rng.choice([("pool_max", 50, 5), ("timeout_ms", 3000, 300), ("max_conns", 400, 40), ("worker_threads", 16, 2)])
    err = {"pool_max": "connection pool exhausted (waited 5000 ms)", "timeout_ms": "request timed out after 300 ms", "max_conns": "too many connections, rejecting client",
           "worker_threads": "work queue full, request rejected"}[key]
    for n in nodes:
        L.add(f"logs/{n}.log", 0.1, "info", "app", n, "effective configuration", **{"pool_max": 50 if key != "pool_max" or n != bad else wrong, "timeout_ms": 3000 if key != "timeout_ms" or n != bad else wrong,
                                                                                  "max_conns": 400 if key != "max_conns" or n != bad else wrong,
                                                                                  "worker_threads": 16 if key != "worker_threads" or n != bad else wrong, "log_level": "info"})
    def hook(t, h, level, msg, kv):
        load = 1.0 if (t // 120) % 2 else 0.2
        if h == bad and rng.random() < 0.7 * load and t > 60:
            return "error", err, {**kv, "status": 503}
        if rng.random() < 0.003:
            return "warn", "slow query", {**kv, "ms": rng.randint(400, 900)}
        return level, msg, kv

    _requests(L, rng, nodes, 600, 0.4, hook, svc="app")
    rows = sorted(L.files[f"logs/{bad}.log"], key=lambda r: r[0])
    anoms = [(f"logs/{bad}.log", 1)] + [(f"logs/{bad}.log", i + 1) for i, (_, ln) in enumerate(rows) if err[:20] in ln][:4]
    return dict(
        symptom="Under load a fraction of requests gets 503, always from the same machine, although all nodes run the same release and the same deploy script.",
        culprit_desc="the node that is misconfigured", culprit=[bad], kind="config-error", anoms=anoms, extra=("config_key", [key], "the configuration key that differs"),
        kw=[key, "config", "configuration", "differs", "drift", "value"], answer=f"{bad} runs with {key}={wrong} while every other node has {key}={good}.")


def scn_cascade(rng: random.Random, L: Log):
    chain = rng.choice([["edge", "api", "billing", "ledger-db"], ["web", "checkout", "payments", "cardvault"], ["gateway", "orders", "inventory", "stock-db"]])
    cause, kind, kw = rng.choice([
        ("disk full on /var/lib/data (no space left on device)", "environment", ["disk", "space", "full"]),
        ("max_connections (100) reached, rejecting new connections", "config-error", ["max_connections", "connections", "limit"]),
        ("TLS certificate expired on 2025-03-18 06:12:00Z", "config-error", ["certificate", "expired", "tls"]),
    ])
    t_root = rng.randint(240, 360)
    delays = [0, rng.randint(8, 25), rng.randint(30, 60), rng.randint(60, 100)]
    order = chain[::-1]  # root first
    for t in range(0, 700, 2):
        for i, svc in enumerate(chain):
            if rng.random() < 0.5:
                L.add(f"logs/{svc}.log", t + rng.random(), "info", svc, svc + "-1", "request ok", ms=rng.randint(8, 80))
    root = chain[-1]
    for k, svc in enumerate(order):
        t0 = t_root + delays[k]
        for j in range(rng.randint(14, 26) if k else rng.randint(10, 18)):
            tt = t0 + j * rng.uniform(1.5, 6)
            if k == 0:
                L.add(f"logs/{svc}.log", tt, "error", svc, svc + "-1", cause)
            elif k == 1:
                L.add(f"logs/{svc}.log", tt, "error", svc, svc + "-1", f"call to {order[0]} failed: timeout after 2000 ms (retry {rng.randint(1, 3)}/3)")
            else:
                L.add(f"logs/{svc}.log", tt, "error", svc, svc + "-1", f"upstream {order[k - 1]} returned 5xx")
    anoms = [(f"logs/{root}.log", i + 1) for i, (_, ln) in enumerate(sorted(L.files[f"logs/{root}.log"], key=lambda r: r[0])) if cause[:15] in ln][:3]
    return dict(
        symptom=f"Customers got errors for about ten minutes starting around 06:0{4 + t_root // 120}. All four services of the {chain[0]} stack logged errors; the alert fired on {chain[0]} first.",
        culprit_desc="the service where it started", culprit=[root], kind=kind, anoms=anoms,
        kw=kw + ["first", "earliest", "root", "upstream"], answer=f"The failure starts in {root} ({cause}); the other services only report its effects.")


def scn_slow_endpoint(rng: random.Random, L: Log):
    hosts = _hosts(rng, 3)
    bad_path = rng.choice(["/api/search", "/api/orders", "/api/inventory", "/api/profile"])
    t_dep = rng.randint(250, 350)
    ver_old, ver_new = "5.%d" % rng.randint(0, 5), "5.%d" % rng.randint(6, 9)
    slow_f = rng.choice([8, 12, 20])
    for h in hosts:
        L.add(f"logs/{h}.log", 0.1, "info", "deploy", h, "release active", version=ver_old)
        L.add(f"logs/{h}.log", t_dep, "info", "deploy", h, "release active", version=ver_new)

    def hook(t, h, level, msg, kv):
        if t >= t_dep and kv["path"] == bad_path:
            kv = {**kv, "ms": int(kv["ms"] * slow_f * rng.uniform(0.8, 1.2))}
            if kv["ms"] > 1500:
                return "warn", "slow request", kv
        return level, msg, kv

    _requests(L, rng, hosts, 600, 0.6, hook)
    anoms = []
    for h in hosts[:2]:
        rows = sorted(L.files[f"logs/{h}.log"], key=lambda r: r[0])
        anoms += [(f"logs/{h}.log", i + 1) for i, (_, ln) in enumerate(rows) if "slow request" in ln][:3]
        anoms += [(f"logs/{h}.log", i + 1) for i, (_, ln) in enumerate(rows) if "release active" in ln and ver_new in ln][:1]
    return dict(
        symptom="Page loads feel slower since the 06:05 release but our dashboards of average latency barely moved.",
        culprit_desc="the endpoint (path) that became slow", culprit=[bad_path], kind="performance", anoms=anoms, extra=("release", [ver_new], "the release after which it got slow"),
        kw=["slow", "latency", "ms", "release", "regress"], answer=f"{bad_path} became about {slow_f}x slower after release {ver_new}.")


def scn_dst(rng: random.Random, L: Log):
    job = rng.choice(["billing-export", "report-mail", "sync-ledger"])
    mode = rng.choice(["fall", "spring"])
    hhmm = rng.choice(["02:15", "02:30", "02:45"])
    hh, mm = map(int, hhmm.split(":"))
    host = "sched-1"
    if mode == "spring":
        date, off_before, off_after = datetime(2025, 3, 30), 1, 2
    else:
        date, off_before, off_after = datetime(2025, 10, 26), 2, 1
    L.t0 = datetime(date.year, date.month, date.day, 0, 0, 0, tzinfo=timezone.utc) - timedelta(days=2)

    def offs(h):
        return f"+{h:02d}:00"

    def t_of(naive, off):
        return (naive - timedelta(hours=off) - L.t0.replace(tzinfo=None)).total_seconds()

    for k in range(-2, 3):
        day = date + timedelta(days=k)
        runs = []
        if k < 0:
            runs = [off_before]
        elif k > 0:
            runs = [off_after]
        elif mode == "fall":
            runs = [off_before, off_after]
        naive = day.replace(hour=hh, minute=mm)
        for off in runs:
            t = t_of(naive, off) + rng.uniform(0, 3)
            L.add("logs/scheduler.log", t, "info", "cron", host, "job started", job=job, local_time=f"{day:%Y-%m-%d}T{hhmm}:00{offs(off)}", tz="Europe/Berlin")
            L.add("logs/scheduler.log", t + rng.randint(30, 90), "info", "cron", host, "job finished", job=job, rows=rng.randint(900, 1100))
        if k == 0 and mode == "spring":
            L.add("logs/scheduler.log", t_of(day.replace(hour=1, minute=59), off_before), "warn", "cron", host, "no matching local time today, nothing to run", job=job,
                  wanted=f"{day:%Y-%m-%d}T{hhmm}", tz="Europe/Berlin")
        for o in ("send-digest", "warm-cache"):
            off = off_before if k < 0 else off_after
            naive4 = day.replace(hour=4, minute=0)
            t = t_of(naive4, off) + rng.uniform(0, 2)
            L.add("logs/scheduler.log", t, "info", "cron", host, "job started", job=o, local_time=f"{day:%Y-%m-%d}T04:00:00{offs(off)}", tz="Europe/Berlin")
            L.add("logs/scheduler.log", t + rng.randint(20, 60), "info", "cron", host, "job finished", job=o, rows=rng.randint(10, 90))
    rows = sorted(L.files["logs/scheduler.log"], key=lambda r: r[0])
    key = f"{date:%Y-%m-%d}"
    anoms = [("logs/scheduler.log", i + 1) for i, (_, ln) in enumerate(rows) if job in ln and (key in ln or "no matching" in ln)][:4]
    sym = (f"The ledger shows the {job} output for the night of the clock change twice, and finance asks why." if mode == "fall"
           else f"On the night the clocks went forward {job} did not run at all, and nobody got an alert.")
    return dict(
        symptom=sym, culprit_desc="the job that is affected", culprit=[job], kind="timezone", anoms=anoms,
        kw=["dst", "daylight", "timezone", "local time", "clock change", "utc", "offset"],
        answer=f"{job} is scheduled in local time ({hhmm} Europe/Berlin), which {'happens twice' if mode == 'fall' else 'does not exist'} on {key}.")


SCENARIOS = [("bad-host", scn_bad_host, 3), ("bad-release", scn_bad_release, 3), ("leak", scn_leak, 3), ("race", scn_race, 4), ("config-drift", scn_config_drift, 4),
             ("cascade", scn_cascade, 4), ("slow-endpoint", scn_slow_endpoint, 3), ("dst", scn_dst, 3)]

_LEVEL = {"bad-host": 3, "bad-release": 3, "leak": 3, "race": 3, "config-drift": 3, "cascade": 3, "slow-endpoint": 3, "dst": 3}

VOICES = [
    "{symptom} The logs of the machines involved are in `logs/`. Work out the root cause. {schema}",
    "On-call handover note: {symptom} I collected whatever logs I could find under `logs/`. Please figure out what is really going on. {schema}",
    "Incident review. What we know: {symptom} The relevant logs are in `logs/` (the files are not in any particular order of importance). {schema}",
    "{symptom} Logs: `logs/`. Find the cause. {schema}",
    "Our SRE channel has been arguing about this for an hour: {symptom} Here are the logs (`logs/`). Settle it with evidence. {schema}",
]


def _schema(culprit_desc: str, extra=None) -> str:
    keys = [f"`culprit` ({culprit_desc})"]
    if extra:
        keys.append(f"`{extra[0]}` ({extra[2]})")
    keys += ["`kind` (one of " + ", ".join(KINDS) + ")", "`evidence_lines` (a list of `path:line` strings pointing at the log lines that prove it)", "`explanation` (one or two sentences)"]
    return "Write `diagnosis.json`: an object with exactly these keys: " + ", ".join(keys[:-1]) + " and " + keys[-1] + "."


def log_task(rng: random.Random, i: int, scn_name: str, fn, style: str) -> Task:
    L = Log(style, rng)
    truth = fn(rng, L)
    files = L.finish()
    start = {}
    for path, lines in files.items():
        start[path] = "\n".join(lines) + "\n"
    fields = {
        "culprit": ({"type": "string_all", "accept": truth["culprit_all"]} if "culprit_all" in truth else {"type": "string_in", "accept": truth["culprit"]}),
        "kind": {"type": "enum", "allowed": KINDS, "accept": accepted(truth["kind"])},
        "evidence_lines": {"type": "evidence", "windows": [{"file": f, "start": ln, "end": ln} for f, ln in truth["anoms"]], "slack": 1},
        "explanation": {"type": "text", "min_len": 20, "any": truth["kw"]},
    }
    schema = _schema(truth["culprit_desc"], truth.get("extra"))
    gold = {"culprit": (" + ".join(truth["culprit_all"]) if "culprit_all" in truth else truth["culprit"][0]), "kind": truth["kind"],
            "evidence_lines": [f"{f}:{ln}" for f, ln in truth["anoms"][:3]], "explanation": truth["answer"]}
    if "extra" in truth:
        key, accept, desc = truth["extra"]
        fields[key] = {"type": "string_in", "accept": accept}
        gold[key] = accept[0]
    if not truth["anoms"]:
        raise RuntimeError(f"{scn_name}: no evidence lines")
    prompt = rng.choice(VOICES).format(symptom=truth["symptom"], schema=schema)
    spec = {"answer_file": "diagnosis.json", "fields": fields}
    nlines = sum(len(v) for v in files.values())
    d = _LEVEL[scn_name] + (1 if nlines > 1800 else 0) + (1 if style == "plain" and scn_name in ("cascade", "race") else 0)
    d = max(1, min(5, d - (1 if nlines < 700 and scn_name in ("bad-host", "dst") else 0)))
    return Task(
        slug=f"{i:02d}-{scn_name}-{style}", prompt=prompt, difficulty=d, kind="fix", lang="text", start=start, hidden=hidden_diag(spec),
        solution={"diagnosis.json": json.dumps(gold, indent=1) + "\n"}, verify="python3 _verify/check.py", pass_mode="json-score",
        protected=sorted(start), timeout_s=60, tags=["log-forensics", scn_name, style], notes={"scenario": scn_name, "style": style, "lines": nlines, "culprit": truth.get("culprit") or truth.get("culprit_all")},
    )


def logs_family(rng: random.Random, n: int):
    i = 0
    plan = []
    for name, fn, w in SCENARIOS:
        plan += [(name, fn)] * w
    rng.shuffle(plan)
    k = 0
    while i < n:
        name, fn = plan[k % len(plan)]
        style = STYLES[(k // len(SCENARIOS) + k) % len(STYLES)]
        k += 1
        i += 1
        yield log_task(rng, i, name, fn, style)
